### PR TITLE
Added explicit cast to ASLWrapper ASL FILTER MASK to build on Carthage for Swift 3.1

### PR DESCRIPTION
**Pull request by guillemf**
When building Log4Swift with Carthage you get the following message
The following build commands failed:
CompileC build/Log4swift.build/Release/log4swift_OSX.build/Objects-normal/x86_64/ASLWrapper.o Log4swift/Objective-c\ wrappers/ASLWrapper.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
Log4swift/Log4swift/Objective-c wrappers/ASLWrapper.m:34:19: error: implicit conversion from 'int' to 'char' changes value from 255 to -1 [-Werror,-Wconstant-conversion]

### CODE REVIEW

**Comment by jduquennoy** [comment]
Thanks a lot for that commit guillemf.
I'll integrate it right now, and work on compilling the lib with xcode 8.3 right after (there are a few warning to get rid of).
